### ISSUE TITLE
Cannot serialize custom property class extending a generic property type

### ISSUE THREAD

**Issue by antoine-guillou** [joffrey-bion/fx-gson#14]
I have a class that extends `SimpleListProperty<Property>`.
On the serialization, it fails on TypeHelper:

```
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

	at org.hildan.fxgson.factories.TypeHelper.withRawType(TypeHelper.java:30)
```

I think the expected behavior should be the one described here: https://stackoverflow.com/questions/21458468/gson-wont-properly-serialise-a-class-that-extends-hashmap

**Comment by joffrey-bion** [comment]
Hi, thanks for opening this issue!

I believe this comes from the fact that I try to get the `ListProperty`'s type argument directly on the user-provided type, which is wrong, because extensions of `ListProperty` might not have a type argument themselves.

I'll take a quick look.

**Comment by joffrey-bion** [comment]
Could you please provide more details about how you declared your types?
I believe a workaround (while waiting for a real fix) would be to use the more abstract `ListProperty<T>` as declared type for your property. But I can't provide more details without knowing your exact situation.

**Comment by antoine-guillou** [comment]
Sure,
With this code you can replicate my error:
```
public class TestListGson extends SimpleListProperty<String> {

    public TestListGson(ObservableList<String> es) {
        super(es);
    }

    public static void main(String[] args) {
        TestListGson myList = new TestListGson(FXCollections.observableArrayList("Item1", "Item2"));

        Gson g = FxGson.coreBuilder().create();
        String j = g.toJson(myList);
        System.out.println(j);
    }
}
```


Changing to:
`public class TestListGson extends ListProperty<String> `
or
`public class TestListGson<T> extends ListProperty<T> ` 
trigger the same error.

**Comment by antoine-guillou** [comment]
A bit more infos:
Same problem if I extend SimpleObjectProperty, no problem if I extend SimpleDoubleProperty.
So it is well the use of  generics which is problematic.

**Comment by joffrey-bion** [comment]
Ok, so technically, your problem is that you're not using a JavaFX property class per se, but your own custom property implementation. It would therefore seem natural that you write your own `TypeAdapter` for your custom property class.

Then FX Gson could be improved to support custom property types serialization, but that is actually getting complicated (there is some pretty deep generics+reflection involved, and those 2 don't mix together very well).

Also, even if I solve the serialization problem by intense generics reflection, you will still have the problem of deserialization of your custom class, which might require anyway some Gson tweaking.

**Comment by antoine-guillou** [comment]
Ok, it totally makes sense.

FYI, on my case I just want to exclude all the superclass fields from the serialization - so I plan to use an [ExclusionStrategy](https://google.github.io/gson/apidocs/com/google/gson/ExclusionStrategy.html).
I am either failing on:
`java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at org.hildan.fxgson.factories.TypeHelper.withRawType(TypeHelper.java:30)`
when extending a collection, or on
`java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at org.hildan.fxgson.factories.JavaFxPropertyTypeAdapterFactory.create(JavaFxPropertyTypeAdapterFactory.java:136)`
when extending an ObjectProperty.

**Comment by joffrey-bion** [comment]
Thanks for the additional info.

What do you mean by "I just want to exclude all superclass fields from serialization"?

Do you mean the reason why you extended `SimpleListProperty` is because you didn't want its fields serialized? If that's the case then FX Gson already takes care of that, you can simply use the original `SimpleListProperty`.

**Comment by antoine-guillou** [comment]
Hi Joffrey,

Forgive my long delay in writing, but I am now back to my issue.
Let me reformulate (I think my issue evolved quite a bit since I opened it...)

I am given a class:
`public class EditableBean<T> extends SimpleObjectProperty<T> 
`
that I have to live with.

This class falls in the cast:
`Type[] typeParams = ((ParameterizedType) type.getType()).getActualTypeArguments();
`
in JavaFxPropertyTypeAdapterFactory create.

To overcome this, I created my own class similar to JavaFxPropertyTypeAdapterFactory except that I return null if EditableBean.class.isAssignableFrom(clazz) and I handle the serialization of my EditableBean on my own.

I think it would be nice to add the concept of classes to be ignored by the JavaFxPropertyTypeAdapterFactory if it makes sense to you.

**Comment by fearlesspixel** [comment]
Hi Joffrey, are you still looking into this issue?

Thanks

**Comment by fearlesspixel** [comment]
Yeah, I'm basically just trying to make simple observable lists with certain generic types as helper classes.

Such as this:

public class PathListProperty extends SimpleListProperty<Path> {
    public PathListProperty() {
        super(FXCollections.observableArrayList());
    }
    public PathListProperty(ObservableList<Path> initialValue) {
        super(initialValue);
    }
}

**Comment by joffrey-bion** [comment]
Then you would anyway need to create your custom TypeAdapter for your custom type, like antoine-guillou needed.
If I write a fix for the FxGsonTypeAdapterFactory, it will simply return null for custom types, allowing you to register your cutom type *after* FxGson's factory.
In the mean time, the only difference is that you need to register your own adapter *before* FxGson's factory.

**Comment by fearlesspixel** [comment]
Okay I thought I had tried that and got another error but I'll look into it again. This is something I'm circling back to as well. I should have time to try again on Monday.

I need to serialize and deserialize. I'm using this as a way to save a config file for paths that a user has selected in the UI.

**Comment by joffrey-bion** [comment]
Ok I see. When deserialisation is needed, you have to declare your own type adapter in order to create instances of the right type.

In order to use your own adapter instead of FxGson's default one, you currently need to register it in front of FxGson's factory:

```java
GsonBuilder builder = new GsonBuilder();
builder.registerTypeAdapter(YourType.class, new YourTypeAdapter();
FxGson.addFxSupport(builder);
Gson gson = builder.create();
```

**Comment by fearlesspixel** [comment]
Okay, so here is what I'm trying to do:

I have a GSON manager class which creates a GSON instance with FxGson and a few type adapters built in.

It includes a method which should allow me to add type adapters dynamically later:
`public static void addTypeAdapter(final Type type, final Object typeAdapter) {
        GSON_BUILDER.registerTypeAdapter(type, typeAdapter);

        GSON =GSON_BUILDER.create();
    }`

I added a static initializer to my custom type which should be able to add it's own support to the manager class like this:
`static {
        PsasGson.addTypeAdapter(PathListProperty.class, new PathListProperty());
    }`

Does that look correct to you?

**Comment by joffrey-bion** [comment]
Well, as far as FxGson is concerned, this will add your custom type adapters *after* FxGson's factory, which will make you run into this bug.

You have a couple options.
1. The simplest: configure the `Gson` in one place with all custom adapters before FxGson's configuration, and no dynamic addition of adapters
2. Keep a list of custom adapters at runtime in your `PsasGson`, and dynamically add to that list. For each addition of type adapter, recreate a new GsonBuilder, add all adapters from the list, and then apply FX support using `FxGson.addFxSupport()`, and then build a new `Gson` from it like you currently do.

As a side note, I would suggest avoiding static state like you are doing with `GSON_BUILDER` and `GSON`. Please use instance fields instead, and inject an instance of your `PsasGson` where you need it.

**Comment by joffrey-bion** [comment]
Reopening for cleaner fix commit (causes issues in changelog)
